import type { MetadataRoute } from "next";

/**
 * PWA web app manifest.
 *
 * Makes Ordilo installable on the phone home screen (Android/Chrome and
 * iOS "Zum Home-Bildschirm"). `display: standalone` removes the browser
 * chrome so the app feels native; `start_url: /home` opens directly on
 * the home tab. Icons are generated by `scripts/generate-icons.mjs`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Ordilo — Dein Familienordner",
    short_name: "Ordilo",
    description:
      "Dein privater AI-Familienordner. Scanne Dokumente, frag Ordilo und behalte alle Fristen im Blick.",
    id: "/home",
    start_url: "/home",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    lang: "de",
    background_color: "#FDFCFA",
    theme_color: "#FDFCFA",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
