import OpenAI from "openai";
import { CHAT_MODEL } from "@/lib/ai/models";

/**
 * LLM-based query expansion.
 *
 * Before searching, the user's query is expanded with synonyms and related
 * terms. This catches cases where the user's vocabulary doesn't match the
 * document's vocabulary:
 *   "Kita" → ["Kita", "Kindergarten", "Krippe", "Tagesstaette", "Hort"]
 *   "Strom" → ["Strom", "Elektrizitaet", "Energie", "Stadtwerke"]
 *   "Arzt" → ["Arzt", "Arztpraxis", "Doktor", "Klinik", "Praxis"]
 *
 * The expanded terms are used as additional keywords in graph traversal
 * and as additional search queries for semantic search.
 *
 * If the LLM call fails, only the original query is used (graceful
 * degradation — expansion is a bonus, not a requirement).
 */

/** Maximum number of expanded terms to generate. */
const MAX_EXPANSION_TERMS = 5;

/** Result of query expansion. */
export interface ExpandedQuery {
  /** The original query string. */
  original: string;
  /** Additional terms/synonyms generated by the LLM. */
  expansions: string[];
  /** All terms (original + expansions), deduplicated. */
  allTerms: string[];
}

/**
 * Expand a search query with synonyms and related German terms.
 *
 * Uses the LLM to generate contextually appropriate synonyms. The LLM is
 * instructed to think in terms of German family documents (invoices, letters,
 * medical records, school communications).
 *
 * @param query - The user's natural-language query.
 * @returns The expanded query with original + synonym terms.
 */
export async function expandQuery(query: string): Promise<ExpandedQuery> {
  const trimmed = query.trim();
  if (!trimmed) {
    return { original: "", expansions: [], allTerms: [] };
  }

  try {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      return { original: trimmed, expansions: [], allTerms: [trimmed] };
    }

    const client = new OpenAI({ apiKey });

    const prompt = `Erstelle Synonyme und verwandte Begriffe fuer eine Dokumentensuche.
Suchanfrage: "${trimmed}"

Generiere bis zu ${MAX_EXPANSION_TERMS} deutsche Synonyme oder verwandte Begriffe,
die in Familien-Dokumenten (Rechnungen, Briefe, Arztbriefe, Schulbriefe) vorkommen koennten.

Beispiele:
- "Kita" → Kindergarten, Krippe, Tagesstaette, Hort
- "Strom" → Elektrizitaet, Energie, Stadtwerke
- "Arzt" → Arztpraxis, Doktor, Klinik, Praxis

Antworte NUR mit den Begriffen, einer pro Zeile. Keine Erklaerung.`;

    const response = await client.chat.completions.create({
      model: CHAT_MODEL,
      messages: [{ role: "user", content: prompt }],
      max_tokens: 100,
      temperature: 0,
    });

    const text = response.choices[0]?.message?.content ?? "";

    // Parse terms (one per line)
    const expansions: string[] = [];
    for (const line of text.split("\n")) {
      const term = line.trim().replace(/^[-•*]\s*/, "");
      if (term && term.length > 2 && !term.includes(":") && term !== trimmed) {
        expansions.push(term);
      }
      if (expansions.length >= MAX_EXPANSION_TERMS) break;
    }

    // Deduplicate (case-insensitive)
    const seen = new Set<string>([trimmed.toLowerCase()]);
    const uniqueExpansions = expansions.filter((e) => {
      const lower = e.toLowerCase();
      if (seen.has(lower)) return false;
      seen.add(lower);
      return true;
    });

    return {
      original: trimmed,
      expansions: uniqueExpansions,
      allTerms: [trimmed, ...uniqueExpansions],
    };
  } catch {
    return { original: trimmed, expansions: [], allTerms: [trimmed] };
  }
}
